name: Nightly Build
on:
  schedule:
    - cron: '0 13 * * *'  # 1pm UTC is 7am CDT

jobs:
  call-multibuild:
    uses: thirdgen88/ignition-docker/.github/workflows/multibuild.yml@main
    with:
      image_tag: nightly
      platforms: linux/amd64,linux/arm64
    secrets:
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
